---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment
  namespace: catalog-demo
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: catalog-demo
  labels:
    app: payments
    service: payments
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: payments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: catalog-demo
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      serviceAccount: payment
      containers:
      - name: payments
        image: ghcr.io/btjimerson/ecommerce-demo/payments
        ports:
        - containerPort: 8080
        env:
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: paymentbackend
              key: stripe-api-key
