name: publish

on:
  push:
    tags: ['v[0-9]+\.[0-9]+\.[0-9]+-?[a-z0-9]*']
env:
  REGISTRY: ghcr.io
  IMAGE_BASE_NAME: ${{ github.repository }}
  CATALOG_NAME: catalog
  FRONTEND_NAME: frontend
  ORDERS_NAME: orders
  PAYMENT_HISTORY_NAME: payment-history
  PAYMENTS_NAME: payments
permissions:
  contents: read
  packages: write
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out out main branch
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Create artifacts
      run: |
        mvn clean package -DskipTests=true -f ${{ env.CATALOG_NAME }}/
        mvn clean package -DskipTests=true -f ${{ env.FRONTEND_NAME }}/
        mvn clean package -DskipTests=true -f ${{ env.ORDERS_NAME }}/
        mvn clean package -DskipTests=true -f ${{ env.PAYMENT_HISTORY_NAME }}/
        mvn clean package -DskipTests=true -f ${{ env.PAYMENTS_NAME }}/
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata for catalog
      id: meta-catalog
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME}}/${{ env.CATALOG_NAME }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=sha
    - name: Build and push catalog
      uses: docker/build-push-action@v3
      with:
        context: ./${{ env.CATALOG_NAME }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta-catalog.outputs.tags }}
        labels: ${{ steps.meta-catalog.outputs.labels }}
    - name: Extract metadata for frontend
      id: meta-frontend
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME}}/${{ env.FRONTEND_NAME }}
    - name: Build and push frontend
      uses: docker/build-push-action@v3
      with:
        context: ./${{ env.FRONTEND_NAME }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta-frontend.outputs.tags }}
        labels: ${{ steps.meta-frontend.outputs.labels }}
    - name: Extract metadata for orders
      id: meta-orders
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME}}/${{ env.ORDERS_NAME }}
    - name: Build and push orders
      uses: docker/build-push-action@v3
      with:
        context: ./${{ env.ORDERS_NAME }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta-orders.outputs.tags }}
        labels: ${{ steps.meta-orders.outputs.labels }}
    - name: Extract metadata for payment history
      id: meta-payment-history
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME}}/${{ env.PAYMENT_HISTORY_NAME }}
    - name: Build and push payment history
      uses: docker/build-push-action@v3
      with:
        context: ./${{ env.PAYMENT_HISTORY_NAME }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta-payment-history.outputs.tags }}
        labels: ${{ steps.meta-payment-history.outputs.labels }}
    - name: Extract metadata for payments
      id: meta-payments
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME}}/${{ env.PAYMENTS_NAME }}
    - name: Build and push payments
      uses: docker/build-push-action@v3
      with:
        context: ./${{ env.PAYMENTS_NAME }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta-payments.outputs.tags }}
        labels: ${{ steps.meta-payments.outputs.labels }}
