name: test

on:
  push:
    branches: [main]
env:
  IMAGE_BASE_NAME: ${{ github.repository }}
  STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
  CATALOG_NAME: catalog
  FRONTEND_NAME: frontend
  ORDERS_NAME: orders
  PAYMENT_HISTORY_NAME: payment-history
  PAYMENTS_NAME: payments
permissions:
  contents: read
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out main branch
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests
      run: |
        mvn test -f ${{ env.CATALOG_NAME }}/
        mvn test -f ${{ env.FRONTEND_NAME }}/
        mvn test -f ${{ env.ORDERS_NAME }}/
        mvn test -f ${{ env.PAYMENT_HISTORY_NAME }}/
        mvn test -f ${{ env.PAYMENTS_NAME }}/
